
function add_64plus64_out64_wrapper_config(this_block)

  % Revision History:
  %
  %   24-Jun-2015  (17:04 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/pcuser/Documents/uWaveMux-mlib-devel/nist_library/math/hdl/vhdl/add_64plus64_out64_wrapper.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('add_64plus64_out64_wrapper');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('a');
  this_block.addSimulinkInport('b');
  this_block.addSimulinkInport('en');
  this_block.addSimulinkInport('sclr');

  this_block.addSimulinkOutport('s');

  s_port = this_block.port('s');
  s_port.setType('UFix_64_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('a').width ~= 64);
      this_block.setError('Input data type for port "a" must have width=64.');
    end

    if (this_block.port('b').width ~= 64);
      this_block.setError('Input data type for port "b" must have width=64.');
    end

    if (this_block.port('en').width ~= 1);
      this_block.setError('Input data type for port "en" must have width=1.');
    end

    this_block.port('en').useHDLVector(false);

    if (this_block.port('sclr').width ~= 1);
      this_block.setError('Input data type for port "sclr" must have width=1.');
    end

    this_block.port('sclr').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../../gitrepo/mlib_devel/nist_library/math/hdl/vhdl/add_64plus64_out64_wrapper.vhd');
  this_block.addFile('../../gitrepo/mlib_devel/nist_library/math/hdl/vhdl/add_64plus64_out64.vhd');
  this_block.addFile('../../gitrepo/mlib_devel/nist_library/math/hdl/ngc/add_64plus64_out64.ngc');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

