
function acc_sm_config(this_block)

  % Revision History:
  %
  %   30-Jun-2015  (14:12 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/pcuser/Documents/uWaveMux-mlib-devel/nist_library/acc/hdl/vhdl/acc_sm.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('acc_sm');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('blanking_start');
  this_block.addSimulinkInport('blanking_stop');
  this_block.addSimulinkInport('channel_count');
  this_block.addSimulinkInport('valid_in');
  this_block.addSimulinkInport('sync_pulse_in');
  this_block.addSimulinkInport('chan_in');

  this_block.addSimulinkOutport('data_out_valid');
  this_block.addSimulinkOutport('acc_valid');
  this_block.addSimulinkOutport('add_reset');
  this_block.addSimulinkOutport('chan_out');

  data_out_valid_port = this_block.port('data_out_valid');
  data_out_valid_port.setType('UFix_1_0');
  data_out_valid_port.useHDLVector(false);
  acc_valid_port = this_block.port('acc_valid');
  acc_valid_port.setType('UFix_1_0');
  acc_valid_port.useHDLVector(false);
  add_reset_port = this_block.port('add_reset');
  add_reset_port.setType('UFix_1_0');
  add_reset_port.useHDLVector(false);
  chan_out_port = this_block.port('chan_out');
  chan_out_port.setType('UFix_8_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('blanking_start').width ~= 16);
      this_block.setError('Input data type for port "blanking_start" must have width=16.');
    end

    if (this_block.port('blanking_stop').width ~= 16);
      this_block.setError('Input data type for port "blanking_stop" must have width=16.');
    end

    if (this_block.port('channel_count').width ~= 8);
      this_block.setError('Input data type for port "channel_count" must have width=8.');
    end

    if (this_block.port('valid_in').width ~= 1);
      this_block.setError('Input data type for port "valid_in" must have width=1.');
    end

    this_block.port('valid_in').useHDLVector(false);

    if (this_block.port('sync_pulse_in').width ~= 1);
      this_block.setError('Input data type for port "sync_pulse_in" must have width=1.');
    end

    this_block.port('sync_pulse_in').useHDLVector(false);

    if (this_block.port('chan_in').width ~= 8);
      this_block.setError('Input data type for port "chan_in" must have width=8.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../../gitrepo/mlib_devel/nist_library/acc/hdl/vhdl/acc_sm.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

